########### 开发环境 ##########
# tomcat
server :
  port : 8888
  tomcat :
    min-spare-threads : 30
    max-threads : 800
    connection-timeout : 5000
    uri-encoding : UTF-8

# dubbo
dubbo :
  port : 20881
  applicationName : lzgyy-platform-service
  registry :
    address : zookeeper://192.168.0.114:2181
  rest :
    port : 8081
    server : tomcat
    contextpath : lzgyy-platform-service
    threads : 500
    accepts : 500

# spring
spring:
  application:
    name : lzgyy-platform
  datasource :
    type : com.alibaba.druid.pool.DruidDataSource
    url : jdbc:mysql://114.215.71.72:3306/lzgyy-platform?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true
    username : root
    password : root
    driverClassName : com.mysql.jdbc.Driver
    initialSize : 5
    minIdle : 20
    maxActive : 200
    maxWait : 60000
    timeBetweenEvictionRunsMillis : 60000
    minEvictableIdleTimeMillis : 300000
    validationQuery : SELECT 1 FROM DUAL
    testWhileIdle : true
    testOnBorrow : false
    testOnReturn : false
    # 打开PSCache，并且指定每个连接上PSCache的大小 
    poolPreparedStatements : true
    maxPoolPreparedStatementPerConnectionSize : 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters : stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties : druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat : true
  http :
    encoding :
      charset : UTF-8
      enabled : true
      force : true
  messages :
    encoding : UTF-8

# logging
logging :
  config : classpath:logback-spring.xml
  level :
    com :
      evisible : 
        blockchain :
          orguser : DEBUG

# banner
banner :
  charset : UTF-8
  location : classpath:config/banner.txt
