
lzgyy:
  iot:
    client:
       # 其它配置
       connect-time: 10 # 线程连接超时，单位秒
       min-period: 10 # 定时任务最小超时时间，单位秒
       # netty客户端配置
       server-ip: 127.0.0.1 # [netty] 服务器IP
       server-port: 8883 # [netty] 服务器端口号
       client-port: 8980 # [netty] 客户端端口号
       is-so-keepalive: true # [netty] 是否保持连接检测对方主机是否崩溃
       is-so-reuseaddr: true # [netty] 地址复用，默认值False。有四种情况可以使用：(1).当有一个有相同本地地址和端口的socket1处于TIME_WAIT状态时，而你希望启动的程序的socket2要占用该地址和端口，比如重启服务且保持先前端口。(2).有多块网卡或用IP Alias技术的机器在同一端口启动多个进程，但每个进程绑定的本地IP地址不能相同。(3).单个进程绑定相同的端口到多个socket上，但每个socket绑定的ip地址不同。(4).完全相同的地址和端口的重复绑定。但这只用于UDP的多播，不用于TCP。
       is-tcp-nodelay: true # [netty] TCP参数，立即发送数据，默认值为Ture（Netty默认为True而操作系统默认为False）。该值设置Nagle算法的启用，改算法将小的碎片数据连接成更大的报文来最小化所发送的报文的数量，如果需要发送一些较小的报文，则需要禁用该算法。Netty默认禁用该算法，从而最小化报文传输延时。
       so-sndbuf: 10485760 # [netty] Socket参数，TCP数据发送缓冲区大小。
       so-revbuf: 10485760 # [netty] Socket参数，TCP数据接收缓冲区大小。
       connect-time-out-millis: 30000 # [netty] 连接超时毫秒数，默认值30000毫秒即30秒。
       writer-idle-time-seconds: 60 # [netty] IdleStateHandler心跳检测器,写超时时间，单位秒
       # ssl配置
       is-ssl: true # [ssl]使用ssl加密
       jks-file:  keystore/client.jks # [ssl] 加密 jks文件地址
       jks-store-pass: 112233445566 # [ssl] 加密jks目标源存储库口令，storepass指定密钥库的密码
       jks-key-pass: 1122334455668 # [ssl] 加密jks目标密钥库口令
       # mqtt配置
       mqtt:
          is-will-flag: false # [mqtt] 是否连接标识
          client-identifier: lzgyy-iot-client-01 # [mqtt] 客户端标识符
          will-topic:  /t1/t2 # [mqtt] 连接主题（isWillFlag为true时配置）
          will-message:  # [mqtt] 连接消息（isWillFlag为true时配置）
          is-has-user-name: true # [mqtt] 是否有用户名
          is-has-password: true # [mqtt] 是否有密码
          user-name: root # [mqtt] 用户名（isHasUserName为true时配置）
          password: 7228788B19B1C983A10D20CB8E87749F0B7EFDD63D119B86693C85409FED1F5C345156305BD52B196962A01927EC0807553BDD05510EA1798AB7927CEF8BF63A # [mqtt]密码（isHasPassword为true时配置）
          is-will-retain: true # [mqtt] 是否保留遗嘱标志（isWillFlag为true时配置）
          will-qos:  0 # [mqtt] 连接服务质量等级（isWillFlag为true时配置）
          is-clean-session: true # [mqtt] 是否清除session
          keep-alive-time:  60 # [mqtt] 保持连接时间，连接允许的最大空闲时间，超过该时间服务端断开连接，单位秒

server:
  port: 8989
 
logging:
        level:
                root: info
                com.lzgyy.plugins.iot: debug